# generated by datamodel-codegen:
#   filename:  scaleplane.openapi.json
#   timestamp: 2026-07-17T17:14:24+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, RootModel


class CompletionNotImplementedResponse(BaseModel):
    detail: str = Field(..., title='Detail')
    message: str = Field(..., title='Message')
    future_capabilities: list[str] = Field(..., title='Future Capabilities')


class CompletionRequest(BaseModel):
    prompt_id: UUID | None = Field(None, title='Prompt Id')
    prompt_slug: str | None = Field(None, title='Prompt Slug')
    tag: str | None = Field('production', title='Tag')
    messages: list[dict[str, Any]] | None = Field(None, title='Messages')
    model: str | None = Field(None, title='Model')


class OrganizationCreate(BaseModel):
    name: str = Field(..., max_length=255, min_length=1, title='Name')
    slug: str = Field(
        ..., max_length=100, min_length=1, pattern='^[a-z0-9-]+$', title='Slug'
    )


class OrganizationResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    slug: str = Field(..., title='Slug')
    name: str = Field(..., title='Name')
    is_default: bool = Field(..., title='Is Default')
    created_at: AwareDatetime = Field(..., title='Created At')


class Name(RootModel[str]):
    root: str = Field(..., max_length=255, min_length=1, title='Name')


class Slug(RootModel[str]):
    root: str = Field(
        ..., max_length=100, min_length=1, pattern='^[a-z0-9-]+$', title='Slug'
    )


class OrganizationUpdate(BaseModel):
    name: Name | None = Field(None, title='Name')
    slug: Slug | None = Field(None, title='Slug')


class ProjectCreate(BaseModel):
    name: str = Field(..., max_length=255, min_length=1, title='Name')
    slug: str = Field(
        ..., max_length=100, min_length=1, pattern='^[a-z0-9-]+$', title='Slug'
    )
    description: str | None = Field(None, title='Description')


class ProjectResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    organization_id: UUID = Field(..., title='Organization Id')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')
    description: str | None = Field(..., title='Description')
    created_at: AwareDatetime = Field(..., title='Created At')


class PromptCreate(BaseModel):
    name: str = Field(..., max_length=255, min_length=1, title='Name')
    slug: str = Field(
        ..., max_length=100, min_length=1, pattern='^[a-z0-9-]+$', title='Slug'
    )
    description: str | None = Field(None, title='Description')
    content: str = Field(..., min_length=1, title='Content')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class PromptEnvironmentTags(BaseModel):
    production: int | None = Field(None, title='Production')
    staging: int | None = Field(None, title='Staging')
    dev: int | None = Field(None, title='Dev')


class PromptResolveResponse(BaseModel):
    prompt_id: UUID = Field(..., title='Prompt Id')
    prompt_slug: str = Field(..., title='Prompt Slug')
    tag: str = Field(..., title='Tag')
    version_id: UUID = Field(..., title='Version Id')
    version_number: int = Field(..., title='Version Number')
    content: str = Field(..., title='Content')
    content_hash: str = Field(..., title='Content Hash')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class PromptResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    project_id: UUID = Field(..., title='Project Id')
    organization_id: UUID = Field(..., title='Organization Id')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')
    description: str | None = Field(..., title='Description')
    created_at: AwareDatetime = Field(..., title='Created At')
    latest_version_number: int | None = Field(None, title='Latest Version Number')
    production_tag_version: int | None = Field(None, title='Production Tag Version')
    environment_tags: PromptEnvironmentTags | None = None


class PromptTagResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    prompt_id: UUID = Field(..., title='Prompt Id')
    name: str = Field(..., title='Name')
    version_id: UUID = Field(..., title='Version Id')
    version_number: int = Field(..., title='Version Number')
    promoted_at: AwareDatetime = Field(..., title='Promoted At')


class PromptVersionCreate(BaseModel):
    content: str = Field(..., min_length=1, title='Content')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    parent_version_id: UUID | None = Field(None, title='Parent Version Id')


class PromptVersionResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    prompt_id: UUID = Field(..., title='Prompt Id')
    version_number: int = Field(..., title='Version Number')
    content: str = Field(..., title='Content')
    content_hash: str = Field(..., title='Content Hash')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    parent_version_id: UUID | None = Field(..., title='Parent Version Id')
    created_by_id: UUID | None = Field(..., title='Created By Id')
    created_at: AwareDatetime = Field(..., title='Created At')


class ProviderType(StrEnum):
    OPENAI = 'openai'
    ANTHROPIC = 'anthropic'
    LOCAL_SLM = 'local_slm'


class RefreshRequest(BaseModel):
    refresh_token: str = Field(..., title='Refresh Token')


class Role(StrEnum):
    OWNER = 'owner'
    ADMIN = 'admin'
    EDITOR = 'editor'
    VIEWER = 'viewer'


class RoutingPolicyCreate(BaseModel):
    name: str = Field(..., max_length=255, min_length=1, title='Name')
    rules: dict[str, Any] | None = Field(None, title='Rules')
    is_active: bool | None = Field(True, title='Is Active')


class RoutingPolicyResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    organization_id: UUID = Field(..., title='Organization Id')
    name: str = Field(..., title='Name')
    rules: dict[str, Any] = Field(..., title='Rules')
    is_active: bool = Field(..., title='Is Active')
    created_at: AwareDatetime = Field(..., title='Created At')


class SwitchOrgRequest(BaseModel):
    organization_id: UUID = Field(..., title='Organization Id')


class TokenResponse(BaseModel):
    access_token: str = Field(..., title='Access Token')
    refresh_token: str = Field(..., title='Refresh Token')
    token_type: str | None = Field('bearer', title='Token Type')
    organization_id: UUID | None = Field(None, title='Organization Id')


class UserLogin(BaseModel):
    email: EmailStr = Field(..., title='Email')
    password: str = Field(..., title='Password')


class UserRegister(BaseModel):
    email: EmailStr = Field(..., title='Email')
    password: str = Field(..., min_length=8, title='Password')
    full_name: str | None = Field(None, title='Full Name')


class UserResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    email: str = Field(..., title='Email')
    full_name: str | None = Field(..., title='Full Name')
    created_at: AwareDatetime = Field(..., title='Created At')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class MemberCreate(BaseModel):
    email: EmailStr = Field(..., title='Email')
    role: Role | None = 'viewer'


class MemberResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    user_id: UUID = Field(..., title='User Id')
    email: str = Field(..., title='Email')
    full_name: str | None = Field(..., title='Full Name')
    role: Role
    created_at: AwareDatetime = Field(..., title='Created At')


class MemberUpdate(BaseModel):
    role: Role


class OrganizationWithRoleResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    slug: str = Field(..., title='Slug')
    name: str = Field(..., title='Name')
    is_default: bool = Field(..., title='Is Default')
    created_at: AwareDatetime = Field(..., title='Created At')
    role: Role


class ProviderCreate(BaseModel):
    name: str = Field(..., max_length=255, min_length=1, title='Name')
    provider_type: ProviderType
    config: dict[str, Any] | None = Field(None, title='Config')
    is_active: bool | None = Field(True, title='Is Active')


class ProviderResponse(BaseModel):
    id: UUID = Field(..., title='Id')
    organization_id: UUID = Field(..., title='Organization Id')
    name: str = Field(..., title='Name')
    provider_type: ProviderType
    config: dict[str, Any] = Field(..., title='Config')
    is_active: bool = Field(..., title='Is Active')
    created_at: AwareDatetime = Field(..., title='Created At')


class OrganizationCreateResponse(BaseModel):
    organization: OrganizationWithRoleResponse
    tokens: TokenResponse
